version: '3'
services:
    client:
      build: ./client/.
      container_name: client
      networks:
        network2:
          aliases:
            - client

    p1:
      build: ./m1/.
      volumes:
       - ./m1/conf:/etc/squid
      networks:
        network2:
          aliases:
            - p1
      container_name: p1

    p2:
      build: ./m2/.
      volumes:
        - ./m2/conf:/etc/squid
      networks:
        network2:
          aliases:
            - p2
      container_name: p2

    p3:
      build: ./m3/.
      volumes:
       - ./m3/conf:/etc/squid
      networks:
        network2:
          aliases:
            - p3
      container_name: p3

networks:
  network1:
    driver: overlay
    internal: true
  network2: